#ifndef VALUES_H_
# define VALUES_H_

namespace Protocole
{
	namespace Server
	{
		enum Procedure
		{
			REJECT = 0,
			ACCEPT = 1,
			FAILURE = 2,
			SUCCESS = 3,
			UPDATE = 4,
			NEW_LOBBY_MESSAGE = 5,
			NEW_FRIEND_MESSAGE = 6,
			CONNECTION_SHUDOWN = 7,
			SEND_FILE = 8,
			MAP_LIST = 9,
			GAME_LIST = 10,
			GAME_CREATION_FAILED = 11,
			GAME_CREATION_SUCCESS = 12,
			JOIN_GAME_FAILED = 13,
			JOIN_GAME_SUCCESS = 14,
			LOBBY_INFORMATION = 15,
			GAME_LOADING = 16,
			GAME_LOADING_FINISHED = 17,
			GAME_SYNCHRONIZATION = 18,
			GAME_SYNCHRONIZATION_FINISHED = 19,
			GAME_STARTED = 20,
			KICK_FROM_LOBBY = 21,
			SEND_ANIMATION = 23,
			ASK_MAP_FAILED = 24,
			ASK_MAP_SUCCEED = 25,
			MAP_DOWNLOAD_FINISH = 26,
			ASK_MAP_SCORES = 27,
			GAME_FINISHED = 28
		};
	}
	namespace Client
	{
		enum Procedure
		{
			INITIALIZE_CONNECTION = 0,
			GAME_LIST = 1,
			JOIN_GAME = 2,
			CREATE_GAME = 3,
			DELETE_GAME = 4,
			SEND_LOBBY_MESSAGE = 5,
			SEND_FRIEND_MESSAGE = 6,
			DISCONNECT = 7,
			MAP_LIST = 8,
			LAUNCH_GAME = 9,
			LOBBY_INFORMATION = 10,
			LEAVE_LOBBY = 11,
			SEND_ANIMATION = 12,
			ASK_MAP = 13,
			GAME_CHANGE_MAP = 14,
			SEND_MAP = 15,
			ASK_SCORES = 16
		};
	}
}

#endif
